### ISSUE TITLE
聊天正常但是embeddings 报错

### ISSUE THREAD

**Issue by BoFan-tunning** [ninehills/chatglm-openai-api#10]
![image](https://user-images.githubusercontent.com/129488076/236652927-00945ffe-010f-492f-8b99-4887933bd05b.png)
2、使用的是
from langchain.embeddings.openai import OpenAIEmbeddings
embeddings = OpenAIEmbeddings(openai_api_key="token1")
3、在你的项目pp文件如使用@app.post("/v1/embeddings")报错信息为404
修改了app文件的调用位置
@app.post("/v1/engines/text-embedding-ada-002/embeddings")

**Comment by BoFan-tunning** [comment]
使用官方openai  api 正常

**Comment by ninehills** [comment]
> 使用官方openai api 正常

这是因为 LangChain的 OpenAIEmbeddings 应该用了一个OpenAI之前的历史接口，我之后做一下兼容就可以了。

**Comment by BoFan-tunning** [comment]
如果现在就想用embedding 的api 是不是 在，把LangChain卸载了装老版本 ，如果是请问是哪个版本？

**Comment by Yuanlw** [comment]
@BoFan-tunning  你这个好了吗？我也遇到这个问题，最后你是怎么处理的

**Comment by ninehills** [comment]
@BoFan-tunning @Yuanlw 本项目已经存档。embedding OpenAI API推荐使用 

https://github.com/michaelfeil/infinity

可以通过容器一键启动，兼容多种embedding模型和reranker模型，还提供各种模型推理优化方案。
