### ISSUE TITLE
chat is

### ISSUE THREAD

**Issue by BoFan-tunning** [ninehills/chatglm-openai-api#16]
![image](https://github.com/ninehills/chatglm-openai-api/assets/129488076/20ba8cb8-53a9-4002-bbee-b770dcd1e386)

**Comment by BoFan-tunning** [comment]
chat can not  use
File "C:\Users\fbai7\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 337, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: '{"detail":[{"loc":["body","messages"],"msg":"field required","type":"value_error.missing"}]}' (HTTP response code was 422)

**Comment by ninehills** [comment]
参考这个 https://github.com/ninehills/chatglm-openai-api/issues/15

选择 Chat接口
