### ISSUE TITLE
使用ngrok 隧道，怎么发布到公网

### ISSUE THREAD

**Issue by eeric** [ninehills/chatglm-openai-api#4]
目前使用内网服务器ip，怎么能换成公网，然后使用curl调用 API

**Comment by ninehills** [comment]
ngrok 每次启动都会显示一个临时的URL。那个就是公网地址。

如果想让域名固定，请查看Readme

**Comment by eeric** [comment]
哦，是要用cloudflare工具吧？

**Comment by ninehills** [comment]
> 哦，是要用cloudflare工具吧？

或者使用ngrok的付费账号，但是cloudflare不要钱，前提是需要你有一个域名在cloudflare上。
