### ISSUE TITLE
能对本地知识库做API吗？

### ISSUE THREAD

**Issue by eeric** [ninehills/chatglm-openai-api#6]
比如：
https://github.com/imClumsyPanda/langchain-ChatGLM/

**Comment by ninehills** [comment]
我相信本地知识库 API 并不是本项目的宗旨，本项目的目标是提供 OpenAI 风格的 LLM API，简单的说只提供 OpenAI 提供的 API。

如果需要提供知识库 API，请考虑OpenAI Cookbook、Langchain 等相关项目。
